var:
  url-repo: https://github.com/ludo2ne/ENSAI-tools   # to call this value : {{< meta var.url-repo >}}

project:
  type: website


website:
  title: "ENSAI tools"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  reader-mode: true
  navbar:
    background: "#447099"
    left:
      - icon: house
        href: index.qmd
        text: Home
      - text: Formater les données
        menu:
          - href: doc/format/csv.qmd
            text: "CSV"
          - href: doc/format/parquet.qmd
            text: "Parquet"
          - href: doc/format/json.qmd
            text: "JSON"
          - href: doc/format/yaml.qmd
            text: "YAML"
      - text: Coder
        menu:
          - href: doc/language/bash.qmd
            text: "Bash"
          - href: doc/language/python.qmd
            text: "Python"
          - href: doc/language/r.qmd
            text: "R"
      - text: Versionner avec Git
        menu:
          - href: doc/git/presentation.qmd
            text: "Présentation"
          - href: doc/git/advanced.qmd
            text: "Usages avancés"
          - href: doc/git/lab.qmd
            text: "TP"
          - href: doc/git/glossary.qmd
            text: "Glossaire"
      - text: Utiliser le Datalab
        menu:
          - href: doc/datalab/intro.qmd
            text: "Introduction"
          - href: doc/datalab/basics.qmd
            text: "Usage basique"
          - href: doc/datalab/advanced.qmd
            text: "Usage avancé"
          - href: doc/datalab/vscode-python.qmd
            text: "VSCode Python"
          - href: doc/datalab/lab.qmd
            text: "TP Découverte"
      - text: Gérer son Projet
        menu:
          - href: doc/project/planning.qmd
            text: "Planning"
          - href: doc/project/lab.qmd
            text: "TP Gestion de projet"
      - text: Rédiger
        menu:
          - href: doc/quarto/markdown.qmd
            text: "Markdown"
          - href: doc/quarto/quarto.qmd
            text: "Introduction"
          - href: doc/quarto/report.qmd
            text: "Rapport de projet"
          - href: doc/quarto/site.qmd
            text: "Site statique"
          - href: doc/quarto/rstudio.qmd
            text: "Using RStudio"
    right:
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

execute:
  freeze: auto

format:
  html:
    theme:
      light: cosmo
      dark: solar
    toc: true
    toc-location: left
    toc-depth: 2
    css: styles.css

from: markdown+emoji
number-sections: true
lightbox: true
