var:
  url-repo: https://github.com/ludo2ne/ENSAI-tools   # to call this value : {{< meta var.url-repo >}}

project:
  type: website


website:
  title: "ENSAI tools"
  repo-url: "{{< meta var.url-repo >}}"
  repo-branch: main
  sidebar:
    tools:
      - icon: github
        href: "{{< meta var.url-repo >}}"
        target: "_blank"
    style: "docked"
    background: "#FFCCE5"
    contents:
      - icon: house
        href: index.qmd
        text: Home
      - section: Format de données
        contents:
          - href: doc/format/csv.qmd
            text: "CSV"
          - href: doc/format/parquet.qmd
            text: "Parquet"
          - href: doc/format/json.qmd
            text: "JSON"
          - href: doc/format/yaml.qmd
            text: "YAML"
      - section: Coder
        contents:
          - href: doc/language/bash.qmd
            text: "Bash"
          - href: doc/language/python.qmd
            text: "Python"
          - href: doc/language/r.qmd
            text: "R"
          - href: doc/language/quality.qmd
            text: "Qualité du code"
          - href: doc/language/iagen.qmd
            text: "Usages de l'IAgen"
      - section: Versionner avec Git
        contents:
          - href: doc/git/presentation.qmd
            text: "Présentation"
          - href: doc/git/advanced.qmd
            text: "Usages avancés"
          - href: doc/git/lab.qmd
            text: "TP"
          - href: doc/git/glossary.qmd
            text: "Glossaire"
      - section: Utiliser le Datalab
        contents:
          - href: doc/datalab/intro.qmd
            text: "Introduction"
          - href: doc/datalab/basics.qmd
            text: "Usage basique"
          - href: doc/datalab/advanced.qmd
            text: "Usage avancé"
          - href: doc/datalab/vscode-python.qmd
            text: "VSCode Python"
          - href: doc/datalab/lab.qmd
            text: "TP Découverte"
      - section: Gérer son Projet
        contents:
          - href: doc/project/planning.qmd
            text: "Planning"
          - href: doc/project/lab.qmd
            text: "TP Gestion de projet"
      - section: Restituer avec Quarto
        contents:
          - href: doc/quarto/markdown.qmd
            text: "Markdown"
          - href: doc/quarto/quarto.qmd
            text: "Introduction"
          - href: doc/quarto/report.qmd
            text: "Rapport de projet"
          - href: doc/quarto/slideshow.qmd
            text: "Diaporama"
          - href: doc/quarto/poster.qmd
            text: "Poster"
          - href: doc/quarto/site.qmd
            text: "Site statique"
          - href: doc/quarto/rstudio.qmd
            text: "Using RStudio"
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Code source]({{< meta var.url-repo >}}){.external target="_blank"}

execute:
  freeze: auto

format:
  html:
    theme:
      light: cosmo
      dark: solar
    toc: true
    toc-location: right
    toc-depth: 2
    css: styles.css
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 300px
      gutter-width: 5rem

from: markdown+emoji
number-sections: true
lightbox: true
